# Generated by Django 3.0.7 on 2020-07-05 06:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import stores.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='가게 특이사항', max_length=30)),
            ],
            options={
                'verbose_name': '가게 뱃지',
                'verbose_name_plural': '가게 뱃지',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='음식 이름', max_length=50)),
                ('description', models.TextField(help_text='음식 설명')),
                ('price', models.IntegerField(help_text='음식 가격')),
                ('image_url', models.TextField(help_text='음식 대표 이미지')),
                ('base_price', models.IntegerField(help_text='음식 가격')),
            ],
            options={
                'verbose_name': '음식 메뉴',
                'verbose_name_plural': '음식 메뉴',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='가게 url', max_length=100)),
                ('name', models.CharField(help_text='가게 이름', max_length=30)),
                ('description', models.TextField(help_text='가게 설명')),
                ('delivery_time', models.CharField(help_text='주문 가능 시간', max_length=30)),
                ('is_delivery', models.BooleanField(help_text='배달 여부')),
                ('is_pickup', models.BooleanField(help_text='테이크아웃 여부')),
                ('delivery_fee', models.IntegerField(help_text='배달 비')),
                ('estimated_prep_time', models.IntegerField(help_text='예상 준비 시간')),
                ('is_partner', models.BooleanField(help_text='파트너인지 여부')),
                ('store_img', models.ImageField(blank=True, help_text='썸네일 이미지', null=True, upload_to=stores.models.store_img_dir)),
                ('address', models.CharField(help_text='가게 주소', max_length=50)),
                ('lat', models.FloatField(help_text='위도')),
                ('lng', models.FloatField(help_text='경도')),
                ('latlng', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='위도 경도 좌표 객체', null=True, srid=4326)),
                ('food_type', models.CharField(choices=[('korean', '한식'), ('chinese', '중식'), ('japanese', '일식')], help_text='가게 요리 분류', max_length=10)),
                ('city', models.CharField(help_text='도시', max_length=30)),
                ('badges', models.ManyToManyField(blank=True, related_name='stores', to='stores.Badge')),
            ],
            options={
                'verbose_name': '가게',
                'verbose_name_plural': '가게',
            },
        ),
        migrations.CreateModel(
            name='OptionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='옵션 카테고리 이름', max_length=30)),
                ('is_required', models.BooleanField(help_text='필수 선택 여부')),
                ('option_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_option_categories', to='stores.OptionCategory')),
            ],
            options={
                'verbose_name': '옵션 카테고리',
                'verbose_name_plural': '옵션 카테고리',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='옵션 이름', max_length=50)),
                ('option_price', models.IntegerField(help_text='옵션 가격')),
                ('option_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='stores.OptionCategory')),
            ],
            options={
                'verbose_name': '옵션',
                'verbose_name_plural': '옵션',
            },
        ),
        migrations.CreateModel(
            name='OpenHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(help_text='월요일', max_length=30)),
                ('tuesday', models.CharField(help_text='화요일', max_length=30)),
                ('wednesday', models.CharField(help_text='수요일', max_length=30)),
                ('thursday', models.CharField(help_text='목요일', max_length=30)),
                ('friday', models.CharField(help_text='금요일', max_length=30)),
                ('saturday', models.CharField(help_text='토요일', max_length=30)),
                ('sunday', models.CharField(help_text='일요일', max_length=30)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_hour', to='stores.Store')),
            ],
            options={
                'verbose_name': '가게 오픈 시간',
                'verbose_name_plural': '가게 오픈 시간',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='메뉴 카테고리', max_length=50)),
                ('menu', models.ManyToManyField(related_name='menu_categories', to='stores.Menu')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Store')),
            ],
            options={
                'verbose_name': '메뉴 카테고리',
                'verbose_name_plural': '메뉴 카테고리',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='option_categories',
            field=models.ManyToManyField(help_text='옵션 카테고리', to='stores.OptionCategory'),
        ),
    ]
