# Generated by Django 3.0.7 on 2020-06-25 11:16

from django.db import migrations, models
import django.db.models.deletion
import stores.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='음식 이름', max_length=50)),
                ('description', models.TextField(help_text='음식 설명')),
                ('price', models.IntegerField(help_text='음식 가격')),
                ('image', models.ImageField(help_text='음식 대표 이미지', upload_to=stores.models.food_img_dir)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='가게 이름', max_length=30)),
                ('description', models.TextField(help_text='가게 설명')),
                ('delivery', models.BooleanField(help_text='배달 여부')),
                ('pickup', models.BooleanField(help_text='테이크아웃 여부')),
                ('delivery_price', models.IntegerField(help_text='배달 비')),
                ('estimated_prep_time', models.IntegerField(help_text='예상 준비 시간')),
                ('is_partner', models.BooleanField(help_text='파트너인지 여부')),
                ('thumb_image', models.ImageField(help_text='썸네일 이미지', upload_to=stores.models.store_img_dir)),
                ('state', models.CharField(choices=[('open', '판매중'), ('close', '판매종료')], help_text='판매 여부', max_length=5)),
                ('address', models.CharField(help_text='가게 주소', max_length=50)),
                ('lat', models.FloatField(help_text='위도')),
                ('lng', models.FloatField(help_text='경도')),
                ('badge', models.CharField(choices=[('NEW', '신상'), ('POPULAR', '인기')], help_text='가게 특징', max_length=7)),
                ('food_type', models.CharField(choices=[('korean', '한식'), ('chinese', '중식'), ('japanese', '일식')], help_text='가게 요리 분류', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='토핑 카테고리', max_length=50)),
                ('name', models.CharField(help_text='토핑 이름', max_length=30)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Food')),
                ('parent_topping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.Topping')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Store'),
        ),
        migrations.CreateModel(
            name='DailyOpenTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monday', models.CharField(help_text='월요일', max_length=30)),
                ('Tuesday', models.CharField(help_text='화요일', max_length=30)),
                ('Wednesday', models.CharField(help_text='수요일', max_length=30)),
                ('Thursday', models.CharField(help_text='목요일', max_length=30)),
                ('Friday', models.CharField(help_text='금요일', max_length=30)),
                ('Saturday', models.CharField(help_text='토요일', max_length=30)),
                ('Sunday', models.CharField(help_text='일요일', max_length=30)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_time', to='stores.Store')),
            ],
        ),
    ]
