# Generated by Django 3.0.8 on 2020-07-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_img',
            field=models.TextField(blank=True, help_text='썸네일 이미지', null=True),
        ),
    ]
