# Generated by Django 3.0.7 on 2020-07-02 10:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latlng',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='위도 경도 좌표 객체', null=True, srid=4326),
        ),
    ]
