# Generated by Django 3.0.7 on 2020-06-29 14:18

from django.db import migrations, models
import django.db.models.deletion
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyopentime',
            options={'verbose_name': '가게 오픈 시간', 'verbose_name_plural': '가게 오픈 시간'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '가게', 'verbose_name_plural': '가게'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name': '토핑', 'verbose_name_plural': '토핑'},
        ),
        migrations.AlterField(
            model_name='dailyopentime',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_opens', to='stores.Store'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='음식 이름', max_length=50)),
                ('description', models.TextField(help_text='음식 설명')),
                ('price', models.IntegerField(help_text='음식 가격')),
                ('image', models.ImageField(help_text='음식 대표 이미지', upload_to=stores.models.food_img_dir)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Menus', to='stores.Store')),
            ],
            options={
                'verbose_name': '음식 메뉴',
                'verbose_name_plural': '음식 메뉴',
            },
        ),
        migrations.AlterField(
            model_name='topping',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='stores.Menu'),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
