# Generated by Django 3.0.7 on 2020-06-29 14:38

from django.db import migrations, models
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20200629_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='thumb_image',
            field=models.ImageField(blank=True, help_text='썸네일 이미지', null=True, upload_to=stores.models.store_img_dir),
        ),
    ]
