# Generated by Django 3.0.8 on 2020-07-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedmenu',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
