# Generated by Django 3.0.8 on 2020-07-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_orderedmenu_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedmenu',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
